name: 'Checkout codebase'
description: 'Checkout codebase'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@master
      with:
        path: src
        ref: ${{ github.head_ref }}
        fetch-depth: 50
      if: github.event_name == 'pull_request'
    - uses: actions/checkout@master
      with:
        path: src
        ref: ${{ github.ref_name }}
        fetch-depth: 50
      if: github.event_name != 'pull_request'
    - uses: actions/cache@v2
      id: cache-checkout
      with:
        path: ./src/
        key: checkout-${{ github.sha }}-v0.1.0
